[package]
name = "tree-sitter-spicedb"
description = "tree-sitter grammar for SpiceDB schemas"
version = "0.0.1"
keywords = ["incremental", "parsing", "spicedb"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/authzed/tree-sitter-spicedb"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20.10"

[build-dependencies]
cc = "1.0"
