#!/bin/sh

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
destination=${1:-"$root/.build/neovim"}

mkdir -p "$destination"
sed 's/@variable\.other\.member/@variable.member/g' \
  "$root/queries/highlights.scm" > "$destination/highlights.scm"
cp "$root/queries/injections.scm" "$destination/injections.scm"
