//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"unicode"
)

func main() {
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprintln(w, "#ifndef TREE_SITTER_SPICEDB_UNICODE_RANGES_H_")
	fmt.Fprintln(w, "#define TREE_SITTER_SPICEDB_UNICODE_RANGES_H_")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Generated by tools/generate_unicode_ranges.go. DO NOT EDIT.")
	fmt.Fprintln(w, "typedef struct { uint32_t first; uint32_t last; } UnicodeRange;")
	fmt.Fprintln(w, "static const UnicodeRange UNICODE_IDENTIFIER_RANGES[] = {")

	start := -1
	end := -1
	count := 0
	for r := 0x80; r <= unicode.MaxRune; r++ {
		valid := unicode.IsLetter(rune(r)) || unicode.IsDigit(rune(r))
		if valid && start < 0 {
			start, end = r, r
		} else if valid && r == end+1 {
			end = r
		} else if start >= 0 {
			fmt.Fprintf(w, "  {0x%X, 0x%X},\n", start, end)
			count++
			start, end = -1, -1
			if valid {
				start, end = r, r
			}
		}
	}
	if start >= 0 {
		fmt.Fprintf(w, "  {0x%X, 0x%X},\n", start, end)
		count++
	}

	fmt.Fprintln(w, "};")
	fmt.Fprintf(w, "#define UNICODE_IDENTIFIER_RANGE_COUNT %d\n", count)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "#endif")
}
